#pragma config(Sensor, S1,     luz1,           sensorEV3_Color)
#pragma config(Sensor, S2,     luz2,           sensorEV3_Color)
#pragma config(Sensor, S3,     luz3,           sensorEV3_Color)
#pragma config(Sensor, S4,     luz4,           sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

long a1,b1,c1,a2,b2,c2,a3,b3,c3,a4,b4,c4; // recebe os valores do sensor R(a1 e a2)G(b1 e b2)B(c1 e c2)
int cor1, cor2, cor3, cor4;

task obterCor(){
	//startTask(tesgetCogetColorName

	while(true){
		//	setMultipleMotors(-28, motorA,motorB);

		//mostrando valores sensores de luz
		getColorRGB(luz1,a1,b1,c1); // colocando para a1 = R, b1 = G e c1 = B do sensor1
		getColorRGB(luz2,a2,b2,c2);	// colocando para a2 = R, b2 = G e c2 = B do sensor2
		getColorRGB(luz3,a3,b3,c3);	// colocando para a2 = R, b2 = G e c2 = B do sensor3
		getColorRGB(luz4,a4,b4,c4);	// colocando para a2 = R, b2 = G e c2 = B do sensor4


		/*
		if(a1>20 && a1<=61 && b1>=21 && b1<=50 && c1>=23 && c1<=40 ){
		//verficando se e prata(silver tap)
		cor1=5;
		}//fim da verificacao do prata(silver tap)SÓ ATIVAR ESSA PARTE SE FOR SILVER TAP NAO ALUMINIO NA RAMPA
		else if(a1>50 && a1<75 && b1>60 && b1<90 && c1>35 && c1<55){
		//verificando se é prata(aluminio)
		cor1=5;
		}//fim verificando se é prata(aluminio)
		if((a2>=15 && a2<=23)&&(b2>=21 && b2<=30)&&(c2>=6 && c2<=20)){
		//verficando se e prata(silver tap)
		cor2=5;
		}//fim da verificacao do prata(silver tap)SÓ ATIVAR ESSA PARTE SE FOR SILVER TAP NAO ALUMINIO NA RAMPA
		else if(a2>50 && a2<75 && b2>60 && b2<90 && c2>35 && c2<55){
		//verificando se é prata(aluminio)
		cor2=5;
		}//fim verificando se é prata(aluminio)

		*/


		if(a1>100 && a1<120 && b1>100 && b1<120  && c1>40 && c1<50){
			//verificando se e  branco
			cor1=1;
		}//fim da verificao do branco
		else if(a1<17 && b1<20 && c1<7){
			//verificando se e  pretol
			cor1=2;
		}//fim da verificao do preto
		else if(a1<55 && a1>=17 && b1>=20 && b1<65 && c1>=7 && c1<30){
			//verificando se e  meiopreto
			cor1=3;
		}//fim da verificacao do meio preto
		else if(a1>=10 && a1<15 && b1>20 && b1<50 && c1<=15){
			//verficando se e verde
			cor1=4;
		}//fim da verificacao do verde
		/*else if(a1>=25 && a1< 29 && b1>=30 && b1<40  && c1>15 && c1<20){
		//verficando se e redutor
		cor1=6;
		}//fim da verificacao do redutor*/
		else{cor1=1;}

		if(a2>100 && a2<120 && b2>100 && b2<120  && c2>40 && c2<50){
			//verificando se e  branco
			cor2=1;
		}// fim da verificacao do branco
		else if(a2<17 && b2<20 && c2<7){
			//verificando se e  pretol
			cor2=2;
		}//fim da verificao do preto
		else if(a2<55 && a2>=17 && b2>=20 && b2<65 && c2>=7 && c2<30){
			//verificando se e  meiopreto
			cor2=3;
		}//fim da verificacao do meio preto
		else if(a2>=10 && a2<15 && b2>20 && b2<50 && c2<=15){
			//verficando se e verde
			cor2=4;
		}//fim verifica verde
		/*else if(a2>=25 && a2< 29 && b2>=30 && b2<40  && c2>15 && c2<20){
		//verficando se e redutor
		cor2=6;
		}//fim da verificacao do redutor*/
		else{cor2=1;}






		if(a3>100 && a3<120 && b3>100 && b3<120  && c3>40 && c3<50){
			//verificando se e  branco
			cor3=1;
		}// fim da verificacao do branco
		else if(a3<17 && b3<20 && c3<7){
			//verificando se e  pretol
			cor3=2;
		}//fim da verificao do preto
		else if(a3<55 && a3>=17 && b3>=20 && b3<65 && c3>=7 && c3<30){
			//verificando se e  meiopreto
			cor3=3;
		}//fim da verificacao do meio preto
		else if(a3>=10 && a3<15 && b3>20 && b3<50 && c3<=15){
			//verficando se e verde
			cor3=4;
		}//fim verifica verde
		/*else if(a2>=25 && a2< 29 && b2>=30 && b2<40  && c2>15 && c2<20){
		//verficando se e redutor
		cor2=6;
		}//fim da verificacao do redutor*/
		else{cor3=1;}





		if(a4>100 && a4<120 && b4>100 && b4<120  && c4>40 && c4<50){
			//verificando se e  branco
			cor4=1;
		}// fim da verificacao do branco
		else if(a4<17 && b4<20 && c4<7){
			//verificando se e  pretol
			cor4=2;
		}//fim da verificao do preto
		else if(a4<55 && a4>=17 && b4>=20 && b4<65 && c4>=7 && c4<30){
			//verificando se e  meiopreto
			cor4=3;
		}//fim da verificacao do meio preto
		else if(a4>=10 && a4<15 && b4>20 && b4<50 && c4<=15){
			//verficando se e verde
			cor4=4;
		}//fim verifica verde
		/*else if(a2>=25 && a2< 29 && b2>=30 && b2<40  && c2>15 && c2<20){
		//verficando se e redutor
		cor2=6;
		}//fim da verificacao do redutor*/
		else{cor4=1;}

	}//fim do while de obter cor
}//fim do obter cor
task main()
{
	bool detalhado=false;
	//int somaS1, somaS2;
	//	startTask(obterCor);
	while (true){
		getColorRawRGB(luz1,a1,b1,c1); // colocando para a1 = R, b1 = G e c1 = B do sensor1
		getColorRawRGB(luz2,a2,b2,c2);
		getColorRawRGB(luz3,a3,b3,c3);
		getColorRawRGB(luz4,a4,b4,c4);

		if (detalhado == true) {
			displayCenteredBigTextLine(5,"------ R  G  B  --------");

			displayCenteredBigTextLine(7,"c1 %d|%d|%d",a1,b1,c1);
			displayCenteredBigTextLine(9,"c2 %d|%d|%d",a2,b2,c2);

			displayCenteredBigTextLine(11,"c3 %d|%d|%d",a3,b3,c3);
			displayCenteredBigTextLine(13,"c4 %d|%d|%d",a4,b4,c4);
			}else {

			int somaS1 = (a1 * 2) + (b1*3) + (c1*1);
			int somaS2 = (a2 * 2) + (b2*3) + (c2*1);
			int somaS3 = (a3 * 2) + (b3*3) + (c3*1);
			int somaS4 = (a4 * 2) + (b4*3) + (c4*1);
			displayCenteredBigTextLine(5,"------ R  G  B  SOMA");
			displayCenteredBigTextLine(7,"cor1 %d",somaS1 );
			displayCenteredBigTextLine(9,"cor2 %d",somaS2 );

			displayCenteredBigTextLine(11,"cor3 %d",somaS3);
			displayCenteredBigTextLine(13,"cor4 %d",somaS4);
		}
		/*displayCenteredBigTextLine(7,"cor1 %d|%d|%d|%d",cor1,a1,b1,c1);
		displayCenteredBigTextLine(9,"cor2 %d|%d|%d|%d",cor2,a2,b2,c2);

		displayCenteredBigTextLine(11,"cor3 %d|%d|%d|%d",cor3,a3,b3,c3);
		displayCenteredBigTextLine(13,"cor4 %d|%d|%d|%d",cor4,a4,b4,c4);
		*/

	}

}
