#pragma config(Sensor, S2,     ,               sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S3,     ,               sensorEV3_Color, modeEV3Color_RGB_Raw)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

    long vermelho, verde, azul;
#include <variaveis_calib.h>
    long S2_R, S2_G, S2_B;
    long S3_R, S3_G, S3_B;

    /*long preto2_R, preto2_G, preto2_B;
    long branco2_R, branco2_G, branco2_B;
    long verde2_R, verde2_G, verde2_B;
    long meioP2_R, meioP2_G, meioP2_B;

    long preto3_R, preto3_G, preto3_B;
    long branco3_R, branco3_G, branco3_B;
    long verde3_R, verde3_G, verde3_B;
    long meioP3_R, meioP3_G, meioP3_B;
    */

    char * filename = "calibrar.txt";

void gravaCores()
{
   writeDebugStreamLine("Testing Longs");

   long fileHandle;

   fileHandle = fileOpenWrite(filename);
   fileWriteLong(fileHandle, S2_R);
   fileWriteLong(fileHandle, S2_G);
   fileWriteLong(fileHandle, S2_B);
   fileWriteLong(fileHandle, S3_R);
   fileWriteLong(fileHandle, S3_G);
   fileWriteLong(fileHandle, S3_B);
   writeDebugStreamLine("fileHandle: %d", fileHandle);
   fileClose(fileHandle);
}

void leAteEnter() {
    	while (getButtonPress(buttonEnter) != 1) {
    	   getColorRGB(S2,vermelho, verde, azul);
         displayTextLine(2,"R:%d", vermelho);
         displayTextLine(3,"G:%d", verde);
         displayTextLine(4,"B:%d", azul);
      }
}

void lerPreto2() {
			leAteEnter();
      preto2_R = vermelho;
      preto2_G = verde;
      preto2_B = azul;
}

void lerBranco2() {
    	leAteEnter();
      branco2_R = vermelho;
      branco2_G = verde;
      branco2_B = azul;
}

void lerVerde2() {
    	leAteEnter();
      verde2_R = vermelho;
      verde2_G = verde;
      verde2_B = azul;
}

void lerMeioP2() {
    	leAteEnter();
      meioP2_R = vermelho;
      meioP2_G = verde;
      meioP2_B = azul;
}

void lerPreto3() {
			leAteEnter();
      preto3_R = vermelho;
      preto3_G = verde;
      preto3_B = azul;
}

void lerBranco3() {
    	leAteEnter();
      branco3_R = vermelho;
      branco3_G = verde;
      branco3_B = azul;
}

void lerVerde3() {
    	leAteEnter();
      verde3_R = vermelho;
      verde3_G = verde;
      verde3_B = azul;
}

void lerMeioP3() {
    	leAteEnter();
      meioP3_R = vermelho;
      meioP3_G = verde;
      meioP3_B = azul;
}

task main()
{
    while (true) {
    	eraseDisplay();
      displayTextLine(2,"Para iniciar a calibracao");
      displayTextLine(3,"Pressione o botao da direita ");
      displayTextLine(4,"ou esquerda");
      waitForButtonPress();
      if(getButtonPress(buttonLeft) == 1) {
       	eraseDisplay();
    	  displayTextLine(2,"Posicione o sensor da esquerda");
    	  eraseDisplay();
    	  waitForButtonPress();
    	  if(getButtonPress(buttonUp) == 1) {
    		  lerPreto2();
    	  }
    	  if(getButtonPress(buttonRight) == 1) {
    		  lerBranco2();
    	  }
        if(getButtonPress(buttonDown) == 1) {
    		  lerVerde2();
    	  }
    	  if(getButtonPress(buttonLeft) == 1) {
    		  lerMeioP2();
    	  }

        eraseDisplay();
        displayTextLine(2,"leitura finalizada");
        delay(1000);
      }
      if(getButtonPress(buttonRight) == 1) {
    	  eraseDisplay();
    	  displayTextLine(2,"Posicione o sensor da direita");
    	  eraseDisplay();
        waitForButtonPress();
				if(getButtonPress(buttonUp) == 1) {
    		  lerPreto3();
    	  }
    	  if(getButtonPress(buttonRight) == 1) {
    		  lerBranco3();
    	  }
        if(getButtonPress(buttonDown) == 1) {
    		  lerVerde3();
    	  }
    	  if(getButtonPress(buttonLeft) == 1) {
    		  lerMeioP3();
    	  }
        eraseDisplay();
        displayTextLine(2,"leitura finalizada");
        delay(1000);

    }
    if (getButtonPress(buttonEnter) == 1) {
    	break;
    }
    delay(1000);
  }
  gravaCores();
}
